---
- name: PHP | Add php5-5.6 PPA
  apt_repository: repo='ppa:ondrej/php5-5.6'
                  state=present
                  update_cache=yes
  sudo: true

- name: PHP | install php packages
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-fpm
    - php5-cli
    - php5-common
    - php5-curl
    - php5-json
    - php-pear
    - php5-gd
    - php5-mcrypt
    - php5-mssql
    - php5-mysql
    - php5-xmlrpc
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php memory_limit
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?memory_limit =" insertafter="^[#|;]?memory_limit =" line="memory_limit = {{ php_memory_limit }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli memory_limit
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?memory_limit =" insertafter="^[#|;]?memory_limit =" line="memory_limit = {{ php_memory_limit }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx max_execution_time
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli max_execution_time
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx post_max_size
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?post_max_size =" insertafter="^[#|;]?post_max_size =" line="post_max_size = {{ php_post_max_size }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli post_max_size
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?post_max_size =" insertafter="^[#|;]?post_max_size =" line="post_max_size = {{ php_post_max_size }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx upload_max_filesize
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?upload_max_filesize =" insertafter="^[#|;]?upload_max_filesize = " line="upload_max_filesize = {{ php_upload_max_filesize }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli upload_max_filesize
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?upload_max_filesize =" insertafter="^[#|;]?upload_max_filesize = " line="upload_max_filesize = {{ php_upload_max_filesize }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx max_execution_time
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli max_execution_time
  lineinfile: dest=/etc/php5/cli/php.ini regexp="[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx display_errors
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?display_errors =" insertafter="^[#|;]?display_errors =" line="display_errors = {{ php_display_errors }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli display_errors
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?display_errors =" insertafter="^[#|;]?display_errors =" line="display_errors = {{ php_display_errors }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx display_startup_errors
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?display_startup_errors =" insertafter="^[#|;]?display_startup_errors =" line="display_startup_errors = {{ php_display_startup_errors }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli display_startup_errors
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?display_startup_errors =" insertafter="^[#|;]?display_startup_errors =" line="display_startup_errors = {{ php_display_startup_errors }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx html_errors
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?html_errors =" insertafter="^[#|;]?html_errors =" line="html_errors = {{ php_html_errors }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli html_errors
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?html_errors =" insertafter="^[#|;]?html_errors =" line="html_errors = {{ php_html_errors }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx date_timezone
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?date_timezone =" insertafter="^[#|;]?date_timezone =" line="date_timezone = {{ php_date_timezone }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli date_timezone
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?date_timezone =" insertafter="^[#|;]?date_timezone =" line="date_timezone = {{ php_date_timezone }}"
  sudo: true
  notify:
    - restart nginx

- name: PHP | configure cgi.fix_pathinfo
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?cgi.fix_pathinfo=" insertafter="^[#|;]?cgi.fix_pathinfo=" line="cgi.fix_pathinfo=0"
  sudo: true
  notify:
    - restart nginx
    - restart fpm

- name: PHP | disable opcache
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^;{{ item }}=" insertafter="^;{{ item }}=" line="{{ item }}=0"
  sudo: true
  with_items:
    - opcache.enable
    - opcache.enable_cli
  notify:
    - restart nginx
    - restart fpm

- name: PHP | configure for nginx 1
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="^[#|;]?group = www" insertafter="^[#|;]?group = www" line="group = vagrant"
  sudo: true
  notify:
    - restart nginx
    - restart fpm

- name: PHP | configure for nginx 2
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="^[#|;]?listen\.group = www" insertafter="^[#|;]?listen\.group = www" line="listen.group = vagrant"
  sudo: true
  notify:
    - restart nginx
    - restart fpm

- name: PHP | configure for nginx 3
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="^[#|;]?listen\.mode = 0660" insertafter="^[#|;]?listen\.mode = 0660" line="listen.mode = 0660"
  sudo: true
  notify:
    - restart nginx
    - restart fpm

- name: PHP | restart fpm
  raw: service php5-fpm restart
  sudo: true